export interface Post {
    slug: string;
    title: string;
    date: string;
    excerpt: string;
    content: string;
    coverImage: string;
    author: string;
    category: string;
}

export const posts: Post[] = [
    {
        slug: 'mastering-pinescript-v6',
        title: 'Mastering Pine Script v6: What\'s New and Why it Matters',
        date: '2026-02-10',
        author: 'PineGen Expert',
        category: 'Development',
        coverImage: 'https://images.unsplash.com/photo-1611974714158-f80e0600ce39?auto=format&fit=crop&q=80&w=1200',
        excerpt: 'Dive into the latest updates in Pine Script v6. From enhanced array handling to simplified color management, learn why v6 is a game-changer for TradingView developers.',
        content: `
# Mastering Pine Script v6

TradingView has recently released Pine Script v6, and it's a significant leap forward for indicator and strategy development. At PineGen, we've optimized our AI engine to handle these changes natively. In this post, we'll explore the core changes and how you can leverage them.

## 1. Simplified Color Management
In previous versions, transparency was often handled via a separate parameter. In v6, \`color.new()\` is the standard, making code cleaner and more intuitive.

## 2. Enhanced Arrays and Collections
Arrays in v6 are more powerful than ever. With improved performance and new helper functions, complex strategy logic that requires tracking historical data points is now much easier to implement.

## 3. Strict Typing Improvements
v6 introduces stricter type checking, which might seem annoying at first but drastically reduces runtime errors in your strategies.

### How PineGen Helps
Our AI generator is trained specifically on v6 syntax. When you describe a strategy, we ensure the output follows the latest best practices, saving you hours of debugging syntax errors.
        `
    },
    {
        slug: 'ai-tradingview-revolution',
        title: 'How AI is Revolutionizing TradingView Strategy Development',
        date: '2026-02-08',
        author: 'AI Researcher',
        category: 'AI & Trading',
        coverImage: 'https://images.unsplash.com/photo-1551288049-bbbda536639a?auto=format&fit=crop&q=80&w=1200',
        excerpt: 'The days of spending weeks learning complex coding syntax are over. Discover how AI generators like PineGen are leveling the playing field for retail traders.',
        content: `
# AI and the Future of Algo Trading

Retail trading has seen a massive shift in the last 5 years. The biggest barrier to entry—coding expertise—is finally falling.

## The Problem with Manual Coding
Most traders are brilliant at spotting patterns but struggle to translate those patterns into code. A single misplaced comma in Pine Script can be the difference between a successful backtest and total frustration.

## The AI Solution
PineGen uses Large Language Models (LLMs) specifically fine-tuned for financial scripts. By providing a natural language prompt, you can generate:
- Complex multi-indicator alerts.
- Backtesting strategies with risk management.
- Custom dashboard indicators.

## Speed to Market
In trading, timing is everything. Being able to test an idea the moment you have it gives you a massive competitive advantage. That's the power of PineGen.
        `
    },
    {
        slug: 'common-pinescript-errors',
        title: '5 Common Pine Script Errors and How PineGen Fixes Them',
        date: '2026-02-05',
        author: 'PineGen Support',
        category: 'Tutorial',
        coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=1200',
        excerpt: 'Struggling with "Undeclared Identifier" or "Mutable Variable" errors? Learn the 5 most common mistakes traders make in Pine Script and how to avoid them.',
        content: `
# 5 Common Pine Script Mistakes

Even experienced developers run into issues with Pine Script's unique architecture. Here are the top 5 we see:

1. **Incorrect Version Declaration**: Forgetting \`//@version=6\` at the top.
2. **Undeclared Identifiers**: Using a variable before it's assigned.
3. **Mutable Variables**: Not using the \`var\` or \`varip\` keywords correctly for state persistence.
4. **Boolean Casting**: Confusing integer inputs with boolean logic.
5. **Loop Performance**: Creating inefficient loops that hit TradingView's execution limits.

### Why use PineGen?
Every script generated by PineGen undergoes a verification step to ensure these common pitfalls are avoided. We use strict v6 rules to ensure your code runs the first time you paste it into the Pine Editor.
        `
    }
];

export async function getPosts() {
    return posts;
}

export async function getPostBySlug(slug: string) {
    return posts.find(p => p.slug === slug);
}
