import Link from "next/link";
import { ChevronLeft, FileText } from "lucide-react";

export default function Terms() {
    return (
        <div className="min-h-screen bg-white dark:bg-page-dark font-sans text-zinc-900 dark:text-white transition-colors duration-300">
            {/* Header */}
            <header className="h-12 sticky top-0 z-50 border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-page-dark/80 backdrop-blur-md flex items-center justify-center px-4">
                <nav className="w-full max-w-[768px] flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <Link href="/" className="p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-xl transition-all">
                            <ChevronLeft size={18} className="text-zinc-500" />
                        </Link>
                        <h1 className="text-sm font-bold tracking-tight">Terms of Service</h1>
                    </div>
                </nav>
            </header>

            <main className="flex flex-col items-center py-20 px-6">
                <div className="w-full max-w-[768px] space-y-12 animate-fade-in">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-emerald-500/10 text-emerald-500 rounded-2xl flex items-center justify-center">
                            <FileText size={24} />
                        </div>
                        <div>
                            <h2 className="text-4xl font-black tracking-tighter leading-none">Usage Framework</h2>
                            <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mt-2">Last updated: February 14, 2026</p>
                        </div>
                    </div>

                    <div className="prose prose-zinc dark:prose-invert max-w-none space-y-10">
                        <section>
                            <h3 className="text-xl font-black tracking-tight mb-4">1. Acceptance of Terms</h3>
                            <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed font-medium">
                                By accessing or using PineScript AI, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-xl font-black tracking-tight mb-4">2. Description of Service</h3>
                            <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed font-medium">
                                PineScript AI provides an AI-powered generator for TradingView Pine Script code. Use of this code is at your own risk. We are not responsible for any financial losses incurred while using strategies or indicators generated by our logic engine.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-xl font-black tracking-tight mb-4">3. User Obligations</h3>
                            <ul className="list-disc pl-6 space-y-3 mt-4 text-zinc-600 dark:text-zinc-400 font-medium">
                                <li>You must provide accurate account information.</li>
                                <li>You are responsible for maintaining the security of your account and API keys.</li>
                                <li>You may not use our service for any illegal, unauthorized, or high-frequency automated scraping purposes.</li>
                            </ul>
                        </section>

                        <section>
                            <h3 className="text-xl font-black tracking-tight mb-4">4. Limitation of Liability</h3>
                            <p className="text-zinc-600 dark:text-zinc-400 leading-relaxed font-medium">
                                In no event shall PineScript AI be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our services, including but not limited to trading losses.
                            </p>
                        </section>

                        <div className="mt-12 pt-8 border-t border-zinc-200 dark:border-zinc-800">
                            <p className="text-sm text-zinc-400 font-bold uppercase tracking-widest">
                                Legal Inquiries? Contact <Link href="mailto:legal@pinegen.ai" className="text-emerald-500 hover:underline">legal@pinegen.ai</Link>
                            </p>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
