export default function Terms() {
    return (
        <div className="min-h-screen bg-white p-8 md:p-24 font-sans text-slate-800 leading-relaxed">
            <div className="max-w-3xl mx-auto">
                <h1 className="text-4xl font-bold mb-8 text-slate-900">Terms of Service</h1>
                <p className="mb-6 italic text-slate-500">Last updated: February 13, 2026</p>

                <section className="mb-10">
                    <h2 className="text-2xl font-semibold mb-4 text-slate-900">1. Acceptance of Terms</h2>
                    <p>By accessing or using PineGen, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.</p>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-semibold mb-4 text-slate-900">2. Description of Service</h2>
                    <p>PineGen provides an AI-powered generator for TradingView Pine Script code. Use of this code is at your own risk. We are not responsible for any financial losses incurred while using strategies generated by our AI.</p>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-semibold mb-4 text-slate-900">3. User Obligations</h2>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>You must provide accurate account information.</li>
                        <li>You are responsible for maintaining the security of your account.</li>
                        <li>You may not use our service for any illegal or unauthorized purpose.</li>
                    </ul>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-semibold mb-4 text-slate-900">4. Limitation of Liability</h2>
                    <p>In no event shall PineGen be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our services.</p>
                </section>

                <div className="mt-12 pt-8 border-t border-slate-100">
                    <p className="text-sm text-slate-500">For legal inquiries, contact legal@pinegen.ai</p>
                </div>
            </div>
        </div>
    );
}
